name: Setup earthly
description: Installs the Earthly binary
branding:
  icon: "sunrise"
  color: "green"
author: Earthly technologies
inputs:
  version:
    description: "version of earthly to use."
    default: "latest"
  use-cache:
    description: "whether to use the cache to store earthly or not"
    default: "true"
runs:
  using: node16
  main: dist/setup/index.js
  post: "dist/cache-save/index.js"
  post-if: inputs.use-cache == 'true'
